### ISSUE TITLE
Problema na responsividade

### ISSUE THREAD

**Issue by Creuma-Kuzola** [EufranioDiogo/3-column-preview-card-component-solution#1]
- [x] [](url)
![Screenshot from 2021-08-28 13-55-02](https://user-images.githubusercontent.com/58623474/131218831-ca395cfc-5972-44b3-bbbb-ac59880cd16c.png)

**Comment by EufranioDiogo** [comment]
Peguei e irei dar uma solução obrigado @Creuma-Kuzola

**Comment by Creuma-Kuzola** [comment]
De nada, @EufranioDiogo 😊

**Comment by EufranioDiogo** [comment]
Desculpa a demora na response mas está feita a correcção e mais uma vez obrigado pelo aviso. @Creuma-Kuzola
